
package com.winxuan.ec.front.controller.cps.webservice.pcn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SalFeedbackServicePortType", targetNamespace = "http://webservice.web.cps.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalFeedbackServicePortType {


    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.web.cps.com")
    @RequestWrapper(localName = "salOrdFb", targetNamespace = "http://webservice.web.cps.com", className = "com.founder.wenx.cps.webservice.pcn.SalOrdFb")
    @ResponseWrapper(localName = "salOrdFbResponse", targetNamespace = "http://webservice.web.cps.com", className = "com.founder.wenx.cps.webservice.pcn.SalOrdFbResponse")
    public int salOrdFb(
        @WebParam(name = "in0", targetNamespace = "http://webservice.web.cps.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.web.cps.com")
        String in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in3
     * @param in0
     * @return
     *     returns com.founder.wenx.cps.webservice.pcn.ArrayOfAnyType
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.web.cps.com")
    @RequestWrapper(localName = "getUncheckOrderInfoView", targetNamespace = "http://webservice.web.cps.com", className = "com.founder.wenx.cps.webservice.pcn.GetUncheckOrderInfoView")
    @ResponseWrapper(localName = "getUncheckOrderInfoViewResponse", targetNamespace = "http://webservice.web.cps.com", className = "com.founder.wenx.cps.webservice.pcn.GetUncheckOrderInfoViewResponse")
    public ArrayOfAnyType getUncheckOrderInfoView(
        @WebParam(name = "in0", targetNamespace = "http://webservice.web.cps.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.web.cps.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.web.cps.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.web.cps.com")
        String in3);

    /**
     * 
     * @param in1
     * @param in0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.web.cps.com")
    @RequestWrapper(localName = "salOrders", targetNamespace = "http://webservice.web.cps.com", className = "com.founder.wenx.cps.webservice.pcn.SalOrders")
    @ResponseWrapper(localName = "salOrdersResponse", targetNamespace = "http://webservice.web.cps.com", className = "com.founder.wenx.cps.webservice.pcn.SalOrdersResponse")
    public int salOrders(
        @WebParam(name = "in0", targetNamespace = "http://webservice.web.cps.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.web.cps.com")
        String in1);

    /**
     * 
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns com.founder.wenx.cps.webservice.pcn.ArrayOfAnyType
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://webservice.web.cps.com")
    @RequestWrapper(localName = "getOrderInfoView", targetNamespace = "http://webservice.web.cps.com", className = "com.founder.wenx.cps.webservice.pcn.GetOrderInfoView")
    @ResponseWrapper(localName = "getOrderInfoViewResponse", targetNamespace = "http://webservice.web.cps.com", className = "com.founder.wenx.cps.webservice.pcn.GetOrderInfoViewResponse")
    public ArrayOfAnyType getOrderInfoView(
        @WebParam(name = "in0", targetNamespace = "http://webservice.web.cps.com")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://webservice.web.cps.com")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://webservice.web.cps.com")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://webservice.web.cps.com")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://webservice.web.cps.com")
        Integer in4);

}
