
package com.winxuan.ec.front.controller.cps.webservice.pcn;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SalFeedbackService", targetNamespace = "http://webservice.web.cps.com", wsdlLocation = "http://cps.mycuo.com/cps/services/SalFeedbackService?wsdl")
public class SalFeedbackService
    extends Service
{

    private final static URL SALFEEDBACKSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SalFeedbackService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = SalFeedbackService.class.getResource(".");
            url = new URL(baseUrl, "http://cps.mycuo.com/cps/services/SalFeedbackService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://cps.mycuo.com/cps/services/SalFeedbackService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SALFEEDBACKSERVICE_WSDL_LOCATION = url;
    }

    public SalFeedbackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalFeedbackService() {
        super(SALFEEDBACKSERVICE_WSDL_LOCATION, new QName("http://webservice.web.cps.com", "SalFeedbackService"));
    }

    /**
     * 
     * @return
     *     returns SalFeedbackServicePortType
     */
    @WebEndpoint(name = "SalFeedbackServiceHttpPort")
    public SalFeedbackServicePortType getSalFeedbackServiceHttpPort() {
        return super.getPort(new QName("http://webservice.web.cps.com", "SalFeedbackServiceHttpPort"), SalFeedbackServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalFeedbackServicePortType
     */
    @WebEndpoint(name = "SalFeedbackServiceHttpPort")
    public SalFeedbackServicePortType getSalFeedbackServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.web.cps.com", "SalFeedbackServiceHttpPort"), SalFeedbackServicePortType.class, features);
    }

}
